# Generated by Django 5.2.7 on 2025-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='art_image',
            field=models.ImageField(blank=True, help_text='Upload image to draw', null=True, upload_to='art_uploads/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.ImageField(blank=True, help_text='Upload GCash screenshot or reference', null=True, upload_to='references/'),
        ),
    ]
