# Generated by Django 5.2.7 on 2025-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_art_image_appointment_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('art', models.ImageField(upload_to='client_arts/')),
                ('reference', models.ImageField(upload_to='client_references/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
