# Generated by Django 5.2.7 on 2025-10-17 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_uploadedart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('art_style', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='uploadedart',
            options={'ordering': ['-date_uploaded'], 'verbose_name': 'Uploaded Art', 'verbose_name_plural': 'Uploaded Arts'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='art_image',
            field=models.ImageField(blank=True, help_text='Upload image to draw', null=True, upload_to='art_uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_reference',
            field=models.ImageField(blank=True, help_text='Upload GCash screenshot or reference', null=True, upload_to='references/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='uploadedart',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='uploadedart',
            name='reference',
            field=models.ImageField(blank=True, null=True, upload_to='references/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])]),
        ),
    ]
