# Generated by Django 5.2.7 on 2025-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='art_image',
            field=models.ImageField(blank=True, help_text='Upload image to draw', null=True, upload_to='art_uploads/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_reference',
            field=models.ImageField(blank=True, help_text='Upload GCash screenshot or reference', null=True, upload_to='references/'),
        ),
        migrations.AlterField(
            model_name='uploadedart',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='uploadedart',
            name='reference',
            field=models.ImageField(blank=True, null=True, upload_to='references/'),
        ),
    ]
